### PR TITLE
Fix/ Subscription hook creation

### PR DESCRIPTION
**Pull request by VikalpP**
## Problem
Not generating proper typing for subscription hooks.
As you can see in the screenshot below, it has correct imports but uses Mutation types for hooks. 

Screenshot 2022-07-08 at 2 57 28 AM

## Solution 

Generate a separate subscription hook as per query def, and use proper typing. 

Screenshot 2022-07-08 at 3 01 58 AM

### CODE REVIEW

**Comment by VikalpP** [comment]
@rintoj  A PR for you. 😄

**Comment by VikalpP** [comment]
Hi @rintoj, it's been a lot of time since I opened PR, Could please have take a look and merge?

**Comment by rintoj** [comment]
@VikalpP, I can not accept this PR because you are missing test cases and code coverage.

**Comment by rintoj** [comment]
I've added this support.

**Pull request closed without merging**
